# Generated by Django 5.0.3 on 2026-02-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_massagebookingmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massagebookingmodel',
            name='massage_type',
            field=models.CharField(max_length=100),
        ),
    ]
